mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    #mysql 配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/climber?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: ---
    #阿里druid连接池驱动配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池的配置信息
    #初始化大小，最小，最大
    initialSize: 2
    minIdle: 2
    maxActive: 3
    #配置获取连接等待超时的时间
    maxWait: 6000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    logAbandoned: true
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    #配置检查
    validationQuery: SELECT 1 FROM DUAL
logging:
  config: classpath:config/logback.xml
